server:
  port: 8082

spring:
  application:
    name: courier-service
  datasource:
    url: jdbc:postgresql://localhost:5432/courier
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

kafka:
  groupId : courierLocation
  topic:
    courierLocation: courier-location
  address: localhost:9092
