server:
  port: 8083

spring:
  application:
    name: store-service
  kafka:
    consumer:
      max-poll-records: 1
  data:
    mongodb:
      database: store_entries
      host: localhost
      port: 27017


kafka:
  groupId : courierLocation
  topic:
    courierLocation: courier-location
  address: localhost:9092
